### PR TITLE
Forum search tools

### PR DESCRIPTION
**Pull request by coneeone**
In the component __SearchTools__, added a ToolBar to filter topics by : 
* content (string passed to the input text)
* popular / recent topics (related tabs)

The topics list (data.topics) and the displayed topics state (topics) are passed from the __ForumContainer__ component into the __SearchTools__ component

_The filtering by tags is not yet functional_

Capture d’écran 2021-04-08 à 10 31 17

### CODE REVIEW

**Review by clemderome — COMMENTED** [review]
Yes, ça m'a l'air good, il faudrait juste changer les double quotes en simple pour rester cohérent avec ce que l'on a fait pour le moment.

**Review by Renemzadi45 — APPROVED** [review]
C'est good pour moi :)

**Review by clemderome — APPROVED** [review]
Nice :)

**Comment by Lenasim** [comment]
il me semble que ma modif sur subnavbar est perdue dns ta PR

**Comment by coneeone** [comment]
- [ ] Floating Action Button to replace action button (https://material-ui.com/components/floating-action-button/)

**Comment by Lenasim** [comment]
- topcis
- btn =>FAB
- remove toggle => show all the time
- remove tags
- css togglebar

**Pull request merged**
